language: rust

before_script:
- sudo apt-get install cmake
- sudo apt-get install bison
- sudo apt-get install flex
- sudo apt-get install gcc
- sudo apt-get install g++
- mkdir build
- cd build
- cmake ..

script: make && ctest --verbose


