language: rust

cache: ccache

before_script:
- (cd optimizer/quickstep/third_party && ./download_and_patch_prerequisites.sh && cd ../../../)
- (mkdir build)
- (cd build &&
  cmake
  -D BUILD_SHARED_LIBS=On
  -D CMAKE_C_FLAGS_DEBUG="$DEBUG_FLAGS"
  -D CMAKE_CXX_FLAGS_DEBUG="$DEBUG_FLAGS"
  -D CMAKE_C_FLAGS_RELEASE="$RELEASE_FLAGS"
  -D CMAKE_CXX_FLAGS_RELEASE="$RELEASE_FLAGS"
  -D CMAKE_EXE_LINKER_FLAGS="$LINKER_FLAGS"
  -D CMAKE_C_COMPILER=$CC
  -D CMAKE_CXX_COMPILER=$CXX
  -D CMAKE_LINKER=$CLINKER
  -D USE_TCMALLOC=0 ..)

install:
- export TEST_JOBS=2;
- if [ "$CC" = "gcc" ]; then
  export CC="gcc-5";
  export CXX="g++-5";
  elif [ "$CC" = "clang" ]; then
  export CC="clang-3.7";
  export CXX="clang++-3.7";
  fi
- export CLINKER=`which gold`
- export DEBUG_FLAGS="-g0";
- export RELEASE_FLAGS="-O0 -DNDEBUG";
- export LINKER_FLAGS="-s"

script:
- (cd build && make -j2)
- (cd build && ctest --verbose)

after_failure:
- df -h
- free -m
- dmesg


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    - george-edison55-precise-backports # For cmake 3.x
    packages:
    - cmake
    - gcc-5
    - cargo
    - rustc
    - bison
    - flex
    - g++-5
    - clang-3.7
    - binutils-gold
    - libprotobuf-dev
    - protobuf-compiler
    - libgtest-dev
    - python-networkx
    - libnuma-dev
    - cmake-data
    - cmake

cache:
  apt: true
