language: rust

cache: ccache

compiler:
- gcc
- clang
- rustc


install:
- export TEST_JOBS=2;
- if [ "$CC" = "gcc" ]; then
  export CC="gcc-5";
  export CXX="g++-5";
  elif [ "$CC" = "clang" ]; then
  export CC="clang-3.7";
  export CXX="clang++-3.7";
  fi
- export CLINKER=`which gold`
- export DEBUG_FLAGS="-g0";
- export RELEASE_FLAGS="-O0 -DNDEBUG";
- export LINKER_FLAGS="-s"


before_script:
- sudo apt-get install cmake
- sudo apt-get install bison
- sudo apt-get install flex
- sudo apt-get install gcc
- sudo apt-get install g++
- $CC --version
- $CXX --version
- $CLINKER --version
- cmake --version
- (cd third_party && ./download_and_patch_prerequisites.sh && cd ../)
- (cd build &&
  cmake -D CMAKE_BUILD_TYPE=$BUILD_TYPE
  -D BUILD_SHARED_LIBS=On
  -D CMAKE_C_FLAGS_DEBUG="$DEBUG_FLAGS"
  -D CMAKE_CXX_FLAGS_DEBUG="$DEBUG_FLAGS"
  -D CMAKE_C_FLAGS_RELEASE="$RELEASE_FLAGS"
  -D CMAKE_CXX_FLAGS_RELEASE="$RELEASE_FLAGS"
  -D CMAKE_EXE_LINKER_FLAGS="$LINKER_FLAGS"
  -D CMAKE_C_COMPILER=$CC
  -D CMAKE_CXX_COMPILER=$CXX
  -D CMAKE_LINKER=$CLINKER
  -D USE_TCMALLOC=0
  -D VECTOR_COPY_ELISION_LEVEL=$VECTOR_COPY_ELISION_LEVEL
  -D ENABLE_COMPARISON_INLINE_EXPANSION=OFF ..)
- ./init.sh
- cd build

script: make && ctest --verbose

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    - george-edison55-precise-backports # For cmake 3.x
    packages:
    - gcc-5
    - g++-5
    - clang-3.7
    - binutils-gold
    - libprotobuf-dev
    - protobuf-compiler
    - libgtest-dev
    - python-networkx
    - libnuma-dev
    - cmake-data
    - cmake

cache:
  apt: true
