[workspace]

members = [
    "api",
    "catalog",
    "cli",
    "common",
    "execution",
    "profiler",
    "resolver",
    "scheduler",
    "server",
    "storage",
    "transaction",
    "types"
]
