[workspace]

members = [
    "api",
    "cli",
    "common",
    "execution",
    "operators",
    "optimizer",
    "parser",
    "profiler",
    "resolver",
    "scheduling",
    "server",
    "single-node",
    "storage",
    "transaction",
    "types"
]
