[package]
name = "conductor"
version = "0.1.0"
authors = ["gaffneyk <kgaff33@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
cli = { path = "../cli" }
execution = { path = "../execution" }

[build-dependencies]
cmake = "0.1.40"
