[package]
name = "hustle-execution"
version = "0.1.0"
authors = ["gaffneyk <kgaff33@gmail.com>"]
edition = "2018"

[dependencies]
hustle-catalog = { path = "../catalog" }
hustle-common = { path = "../common" }
hustle-storage = { path = "../storage" }
