[package]
name = "types"
version = "0.1.0"
authors = ["Matt Dutson <dutson@wisc.edu>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.39"
