[package]
name = "hustle-catalog"
version = "0.1.0"
authors = ["gaffneyk <kgaff33@gmail.com>"]
edition = "2018"

[dependencies]
hustle-types = { path = "../types" }
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.40"
