[package]
name = "cli"
version = "0.1.0"
authors = ["gaffneyk <kgaff33@gmail.com>"]
edition = "2018"

[dependencies]
optimizer = { path = "../optimizer" }
execution = { path = "../execution" }
rustyline = "4.1.0"
