[package]
name = "server"
version = "0.1.0"
authors = ["gaffneyk <kgaff33@gmail.com>"]
edition = "2018"

[dependencies]
message = { path = "../message" }
transaction = { path = "../transaction" }
optimizer = { path = "../optimizer" }
execution = { path = "../execution" }
profiler = { path = "../profiler" }
hustle-parser = { git = "https://github.com/UWHustle/hustle-parser" }
crossbeam-utils = "0.6.5"
byteorder = "1.3.1"
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.39"
