[package]
name = "resolver"
version = "0.1.0"
authors = ["gaffneyk <kgaff33@gmail.com>"]
edition = "2018"

[dependencies]
message = { path = "../message" }
profiler = { path = "../profiler" }
serde = { version = "1.0.92", features = ["derive"] }
serde_json = "1.0.39"
