# CMake generated Testfile for 
# Source directory: /Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver
# Build directory: /Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(quickstep_queryoptimizer_tests_resolver_aggregate "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Aggregate.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Aggregate.test")
add_test(quickstep_queryoptimizer_tests_resolver_copy "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Copy.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Copy.test")
add_test(quickstep_queryoptimizer_tests_resolver_create "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Create.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Create.test")
add_test(quickstep_queryoptimizer_tests_resolver_delete "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Delete.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Delete.test")
add_test(quickstep_queryoptimizer_tests_resolver_drop "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Drop.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Drop.test")
add_test(quickstep_queryoptimizer_tests_resolver_index "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Index.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Index.test")
add_test(quickstep_queryoptimizer_tests_resolver_insert "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Insert.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Insert.test")
add_test(quickstep_queryoptimizer_tests_resolver_join "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Join.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Join.test")
add_test(quickstep_queryoptimizer_tests_resolver_select "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Select.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Select.test")
add_test(quickstep_queryoptimizer_tests_resolver_setoperation "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/SetOperation.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/SetOperation.test")
add_test(quickstep_queryoptimizer_tests_resolver_update "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Update.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/resolver/Update.test")
