[package]
name = "storage"
version = "0.1.0"
authors = ["gaffneyk <kpgaffney@wisc.edu>"]

[dependencies]
memmap = "0.7.0"

[lib]
name = "storage"
path = "src/lib.rs"
crate-type = ["rlib", "dylib", "staticlib"]