#line 2 "lexer.c"

#line 4 "lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart (FILE *input_file ,yyscan_t yyscanner );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void yy_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yy_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void yypop_buffer_state (yyscan_t yyscanner );

static void yyensure_buffer_stack (yyscan_t yyscanner );
static void yy_load_buffer_state (yyscan_t yyscanner );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *yyalloc (yy_size_t ,yyscan_t yyscanner );
void *yyrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void yyfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 163
#define YY_END_OF_BUFFER 164
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[599] =
    {   0,
        0,    0,  164,  163,  162,  154,  137,  163,  149,  155,
      158,  153,  141,  151,  143,  157,  147,  160,  150,  146,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  138,  139,    0,  159,  144,
        0,  147,  148,  152,  145,  156,  161,  161,  161,  161,
      161,  161,  161,   10,  161,  161,  161,   17,  161,  161,
      161,  161,  161,  161,  161,  161,   41,  161,  161,  161,
      161,   46,  161,  161,  161,  161,  161,  161,  161,  161,
      161,   61,  161,  161,   64,   73,  161,  161,  161,  161,

      161,   81,  161,   86,   88,   89,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  120,  161,  161,  161,  161,  161,  161,  161,  161,
        0,  142,  161,  161,    3,  161,    5,  161,  161,    8,
        9,   11,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,   45,  161,  161,  161,  161,  161,
      161,  161,   55,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,   76,  161,  161,  161,
      161,   82,  161,  161,  161,  161,  161,  161,  161,  161,

      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  111,  161,  161,  115,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,    0,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,   19,   20,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,   38,  161,  161,   42,   43,   44,  161,  161,
      161,  161,  161,   52,  161,  161,  161,   57,   58,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,   72,
      161,   75,   77,   78,  161,  161,  161,  161,   85,  161,

      161,  161,   92,  161,   94,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  112,  161,  161,  161,  117,  119,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  130,  161,  132,  161,
      161,  135,  140,    1,  161,    4,    6,  161,  161,  161,
      161,   15,  161,  161,   21,  161,  161,  161,  161,  161,
      161,   28,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  161,  161,  161,  161,   59,  161,  161,
      161,   65,  161,   68,  161,  161,  161,  161,   79,   80,
      161,  161,  161,   90,   91,  161,  161,  161,  161,   98,

       99,  100,  161,  161,  161,  161,  161,  161,  161,  161,
      109,  161,  161,  161,  116,  161,  161,  161,  161,  124,
      161,  161,  127,  161,  161,  161,  133,  161,  161,    2,
      161,   12,  161,   14,  161,  161,  161,   23,   24,  161,
      161,   27,  161,  161,  161,  161,   37,   39,  161,   47,
       48,  161,   50,  161,   53,  161,  161,   60,   62,  161,
      161,  161,   69,  161,  161,   74,  161,  161,   87,  161,
       95,  161,  161,  161,  161,  103,  161,  161,  106,  161,
      161,  161,  161,  114,  161,  161,  161,  161,  125,  126,
      128,  129,  161,  134,  161,    7,  161,   16,   18,   22,

      161,  161,   29,  161,   34,  161,  161,  161,  161,   51,
      161,   56,  161,   66,  161,   70,  161,   83,   84,  161,
      161,   97,  161,  161,  104,  105,  107,  161,  161,  161,
      161,  161,  122,  161,  131,  136,  161,   25,  161,  161,
       33,  161,   36,   40,  161,  161,  161,  161,  161,  161,
      161,  161,  161,  108,  110,  161,  161,  161,  161,  161,
      161,  161,  161,  161,   49,   54,   63,   67,   71,   93,
       96,  101,  161,  113,  118,  161,  123,  161,   26,  161,
      161,   35,  102,  161,  161,  161,  161,  121,  161,   30,
       31,   13,  161,  161,  161,  161,   32,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    4,    5,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,   16,   17,
       18,   19,    1,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
        1,    1,    1,    1,   46,    1,   47,   47,   47,   47,

       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   48,
       47,   47,    1,   49,    1,   50,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[51] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    4,    3,    3,    1,    1
    } ;

static yyconst flex_int16_t yy_base[602] =
    {   0,
        0,    0,  610,  611,  611,  611,  611,  603,  611,  611,
      611,  611,  611,  611,  593,  611,   38,  611,   36,   38,
       37,   28,   44,   45,   54,   66,   30,  587,   63,  572,
      581,   74,  584,   59,   79,   86,  563,   87,   85,   98,
       75,   63,   99,  596,    0,  552,  611,  594,  593,  583,
      582,  115,  611,  611,  611,  611,    0,  562,  556,  571,
      554,   98,  111,  570,  552,  551,  113,    0,  551,  564,
      109,   90,  550,  547,  118,  547,    0,  550,  561,  544,
      558,    0,  558,  123,  551,  547,  113,  543,  542,  541,
      533,    0,  540,  540,  131,  538,  542,  525,  543,  116,

      528,  527,  534,  539,    0,  540,  523,  537,  523,  539,
      143,  534,  132,  150,  531,  105,  515,  122,  534,  522,
      529,    0,  146,  152,  529,  523,  146,  155,  526,  151,
        0,  611,  512,  520,    0,  523,    0,  522,  514,    0,
        0,    0,  524,  509,  508,  513,  498,  165,  517,  151,
      506,  161,  517,  498,  498,  514,  173,  509,  510,  511,
      491,  494,  501,  503,    0,  506,  170,  487,  493,  492,
      483,  490,  496,  487,  497,  477,  488,  481,  490,  489,
      473,  487,  171,  172,  470,  476,    0,  469,  483,  478,
      483,  175,  473,  465,  478,  477,  463,  460,  465,  471,

      474,  463,  457,  455,  466,  451,  466,  465,  455,  463,
      466,  454,  445,  456,  451,  443,  456,  455,    0,  447,
      442,  443,  442,  448,  439,  164,  452,  438,  430,  429,
      426,  428,  170,  443,  438,  458,  424,  428,  424,  423,
      415,  436,  429,  419,  422,  430,  433,    0,    0,  422,
      431,  418,  421,  417,  408,  407,  407,  420,  422,  402,
      404,  401,    0,  417,  410,    0,    0,    0,  402,  401,
      395,  395,  413,    0,  408,  397,  402,    0,    0,  394,
      395,  390,  403,  382,  396,  386,  385,  397,  383,    0,
      388,    0,    0,    0,  379,  390,  388,  375,    0,  390,

      376,  375,    0,  383,    0,  378,  385,  388,  363,  382,
      381,  367,  366,  359,  378,  380,  367,  378,  360,  357,
      374,    0,  359,  371,  368,  357,    0,  352,  363,  348,
      354,  346,  346,  358,  343,  358,    0,  341,    0,  356,
      345,  344,  611,    0,  344,    0,    0,  331,  348,  341,
      349,    0,  348,  348,    0,  331,  336,  329,  339,  329,
      341,    0,  331,  343,  331,  324,  336,  332,  325,  333,
      317,  317,  316,  325,  315,  309,  324,    0,  323,  324,
      319,  322,  325,    0,  305,  323,  304,  310,    0,    0,
      307,  308,  299,    0,    0,  298,  316,  312,  297,    0,

        0,    0,  295,  308,  296,  306,  291,  304,  305,  298,
        0,  305,  290,  284,    0,  285,  301,  296,  286,    0,
      294,  293,    0,  284,  277,  294,    0,  271,  272,    0,
      287,    0,  288,    0,  276,  284,  283,    0,    0,  284,
      285,    0,  265,  265,  263,  185,    0,    0,  279,    0,
        0,  272,    0,  266,    0,  270,  264,    0,    0,  276,
      272,  263,    0,  270,  268,    0,  265,  259,    0,  261,
        0,  260,  243,  258,  252,    0,  241,  259,    0,  258,
      259,  258,  251,    0,  258,  255,  239,  252,    0,    0,
        0,    0,  243,    0,  234,    0,  235,    0,    0,    0,

      232,  242,  223,  244,    0,  246,  243,  226,  223,    0,
      230,    0,  223,    0,  230,    0,  238,    0,    0,  225,
      225,    0,  216,  234,    0,    0,    0,  216,  224,  220,
      215,  212,    0,  226,    0,    0,  225,    0,  215,  188,
        0,  216,    0,    0,  222,  219,  220,  199,  203,  208,
      214,  215,  214,    0,    0,  198,  192,  207,  211,  197,
      187,  205,  196,  199,    0,    0,    0,    0,    0,    0,
        0,    0,  184,    0,    0,  187,    0,  196,    0,  180,
      186,    0,    0,  184,  183,  191,  190,    0,  174,    0,
      174,    0,  123,  113,   48,   31,    0,  611,  227,  229,

       60
    } ;

static yyconst flex_int16_t yy_def[602] =
    {   0,
      598,    1,  598,  598,  598,  598,  598,  599,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  598,  598,  599,  599,  598,
      598,  598,  598,  598,  598,  598,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,

      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      601,  598,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,

      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  598,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,

      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  598,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,

      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,

      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,    0,  598,  598,

      598
    } ;

static yyconst flex_int16_t yy_nxt[662] =
    {   0,
        4,    5,    4,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,    4,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   45,   45,    4,   45,   44,   46,   47,
       51,   67,   52,   53,   54,   55,   56,   58,   59,   60,
       89,   61,  236,   69,   74,  597,   90,   62,   75,   63,
       70,   68,   76,   79,   64,   65,   66,   71,   77,  596,
       72,   78,  127,   73,   80,   85,   81,   92,   93,   82,
      128,   83,  102,   86,   94,   95,   84,   99,  103,   87,

       96,  100,   88,  104,  117,  109,  113,  124,  118,  125,
      114,  105,  126,  153,  115,  106,  110,  119,  107,  108,
      116,  120,  111,  154,  121,  129,  130,   51,  137,   52,
      139,  122,  595,  140,  123,  215,  138,  145,  146,  150,
      151,  152,  157,  172,  167,  189,  216,  190,  158,  173,
      168,  147,  218,  180,  141,  159,  160,  169,  181,  204,
      219,  594,  200,  182,  205,  223,  201,  229,  183,  184,
      202,  206,  225,  224,  207,  208,  230,  209,  231,  226,
      210,  251,  211,  234,  212,  254,  247,  213,  248,  235,
      252,  232,  260,  270,  287,  289,  261,  331,  255,  332,

      271,  297,  339,  249,  506,  290,  340,  298,  507,  288,
      562,  593,  592,  591,  590,  589,  588,  587,  586,  585,
      584,  583,  582,  581,  580,  579,  563,   48,  578,   48,
       48,   57,   57,  577,  576,  575,  574,  573,  572,  571,
      570,  569,  568,  567,  566,  565,  564,  561,  560,  559,
      558,  557,  556,  555,  554,  553,  552,  551,  550,  549,
      548,  547,  546,  545,  544,  543,  542,  541,  540,  539,
      538,  537,  536,  535,  534,  533,  532,  531,  530,  529,
      528,  527,  526,  525,  524,  523,  522,  521,  520,  519,
      518,  517,  516,  515,  514,  513,  512,  511,  510,  509,

      508,  505,  504,  503,  502,  501,  500,  499,  498,  497,
      496,  495,  494,  493,  492,  491,  490,  489,  488,  487,
      486,  485,  484,  483,  482,  481,  480,  479,  478,  477,
      476,  475,  474,  473,  472,  471,  470,  469,  468,  467,
      466,  465,  464,  463,  462,  461,  460,  459,  458,  457,
      456,  455,  454,  453,  452,  451,  450,  449,  448,  447,
      446,  445,  444,  443,  442,  441,  440,  439,  438,  437,
      436,  435,  434,  433,  432,  431,  430,  429,  428,  427,
      426,  425,  424,  423,  422,  421,  420,  419,  418,  417,
      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,

      406,  405,  404,  403,  402,  401,  400,  399,  398,  397,
      396,  395,  394,  393,  392,  391,  390,  389,  388,  387,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  354,  353,  352,  351,  350,  349,  348,  347,
      346,  345,  344,  343,  342,  341,  338,  337,  336,  335,
      334,  333,  330,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,

      302,  301,  300,  299,  296,  295,  294,  293,  292,  291,
      286,  285,  284,  283,  282,  281,  280,  279,  278,  277,
      276,  275,  274,  273,  272,  269,  268,  267,  266,  265,
      264,  263,  262,  259,  258,  257,  256,  253,  250,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  233,
      228,  227,  222,  221,  220,  217,  214,  203,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  188,  187,  186,
      185,  179,  178,  177,  176,  175,  174,  171,  170,  166,
      165,  164,  163,  162,  161,  156,  155,  149,  148,  144,
      143,  142,  136,  135,  134,  133,   50,   50,   49,   49,

      132,  131,  112,  101,   98,   97,   91,   50,   49,  598,
        3,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598
    } ;

static yyconst flex_int16_t yy_chk[662] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       17,   22,   17,   19,   19,   20,   20,   21,   21,   21,
       27,   21,  601,   23,   24,  596,   27,   21,   24,   21,
       23,   22,   24,   25,   21,   21,   21,   23,   24,  595,
       23,   24,   42,   23,   25,   26,   25,   29,   29,   25,
       42,   25,   34,   26,   29,   29,   25,   32,   34,   26,

       29,   32,   26,   35,   39,   36,   38,   41,   39,   41,
       38,   35,   41,   72,   38,   35,   36,   40,   35,   35,
       38,   40,   36,   72,   40,   43,   43,   52,   62,   52,
       63,   40,  594,   63,   40,  116,   62,   67,   67,   71,
       71,   71,   75,   87,   84,  100,  116,  100,   75,   87,
       84,   67,  118,   95,   63,   75,   75,   84,   95,  113,
      118,  593,  111,   95,  113,  123,  111,  127,   95,   95,
      111,  114,  124,  123,  114,  114,  127,  114,  128,  124,
      114,  150,  114,  130,  114,  152,  148,  114,  148,  130,
      150,  128,  157,  167,  183,  184,  157,  226,  152,  226,

      167,  192,  233,  148,  446,  184,  233,  192,  446,  183,
      540,  591,  589,  587,  586,  585,  584,  581,  580,  578,
      576,  573,  564,  563,  562,  561,  540,  599,  560,  599,
      599,  600,  600,  559,  558,  557,  556,  553,  552,  551,
      550,  549,  548,  547,  546,  545,  542,  539,  537,  534,
      532,  531,  530,  529,  528,  524,  523,  521,  520,  517,
      515,  513,  511,  509,  508,  507,  506,  504,  503,  502,
      501,  497,  495,  493,  488,  487,  486,  485,  483,  482,
      481,  480,  478,  477,  475,  474,  473,  472,  470,  468,
      467,  465,  464,  462,  461,  460,  457,  456,  454,  452,

      449,  445,  444,  443,  441,  440,  437,  436,  435,  433,
      431,  429,  428,  426,  425,  424,  422,  421,  419,  418,
      417,  416,  414,  413,  412,  410,  409,  408,  407,  406,
      405,  404,  403,  399,  398,  397,  396,  393,  392,  391,
      388,  387,  386,  385,  383,  382,  381,  380,  379,  377,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  361,  360,  359,  358,  357,  356,
      354,  353,  351,  350,  349,  348,  345,  342,  341,  340,
      338,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      326,  325,  324,  323,  321,  320,  319,  318,  317,  316,

      315,  314,  313,  312,  311,  310,  309,  308,  307,  306,
      304,  302,  301,  300,  298,  297,  296,  295,  291,  289,
      288,  287,  286,  285,  284,  283,  282,  281,  280,  277,
      276,  275,  273,  272,  271,  270,  269,  265,  264,  262,
      261,  260,  259,  258,  257,  256,  255,  254,  253,  252,
      251,  250,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  232,  231,  230,  229,
      228,  227,  225,  224,  223,  222,  221,  220,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  199,  198,  197,

      196,  195,  194,  193,  191,  190,  189,  188,  186,  185,
      182,  181,  180,  179,  178,  177,  176,  175,  174,  173,
      172,  171,  170,  169,  168,  166,  164,  163,  162,  161,
      160,  159,  158,  156,  155,  154,  153,  151,  149,  147,
      146,  145,  144,  143,  139,  138,  136,  134,  133,  129,
      126,  125,  121,  120,  119,  117,  115,  112,  110,  109,
      108,  107,  106,  104,  103,  102,  101,   99,   98,   97,
       96,   94,   93,   91,   90,   89,   88,   86,   85,   83,
       81,   80,   79,   78,   76,   74,   73,   70,   69,   66,
       65,   64,   61,   60,   59,   58,   51,   50,   49,   48,

       46,   44,   37,   33,   31,   30,   28,   15,    8,    3,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lexer.l"
#line 2 "lexer.l"
#include "parse_node.h"
#include "parser.h"
#include <stdio.h>
#line 782 "lexer.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (yyscan_t yyscanner );

int yyget_debug (yyscan_t yyscanner );

void yyset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra (yyscan_t yyscanner );

void yyset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *yyget_in (yyscan_t yyscanner );

void yyset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *yyget_out (yyscan_t yyscanner );

void yyset_out  (FILE * out_str ,yyscan_t yyscanner );

yy_size_t yyget_leng (yyscan_t yyscanner );

char *yyget_text (yyscan_t yyscanner );

int yyget_lineno (yyscan_t yyscanner );

void yyset_lineno (int line_number ,yyscan_t yyscanner );

YYSTYPE * yyget_lval (yyscan_t yyscanner );

void yyset_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (yyscan_t yyscanner );
#else
extern int yywrap (yyscan_t yyscanner );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param ,yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 12 "lexer.l"

#line 1017 "lexer.c"

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		yy_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 599 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 611 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 13 "lexer.l"
{ return TK_ABORT; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 14 "lexer.l"
{ return TK_ACTION; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 15 "lexer.l"
{ return TK_ADD; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 16 "lexer.l"
{ return TK_AFTER; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 17 "lexer.l"
{ return TK_ALL; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 18 "lexer.l"
{ return TK_ALTER; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 19 "lexer.l"
{ return TK_ANALYZE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 20 "lexer.l"
{ return TK_AND; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 21 "lexer.l"
{ return TK_ANY; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 22 "lexer.l"
{ return TK_AS; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 23 "lexer.l"
{ return TK_ASC; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 24 "lexer.l"
{ return TK_ATTACH; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 25 "lexer.l"
{ return TK_AUTOINCR; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 26 "lexer.l"
{ return TK_BEFORE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 27 "lexer.l"
{ return TK_BEGIN; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 28 "lexer.l"
{ return TK_BETWEEN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 29 "lexer.l"
{ return TK_BY; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 30 "lexer.l"
{ return TK_CASCADE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 31 "lexer.l"
{ return TK_CASE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 32 "lexer.l"
{ return TK_CAST; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 33 "lexer.l"
{ return TK_CHECK; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 34 "lexer.l"
{ return TK_COLLATE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 35 "lexer.l"
{ return TK_COLUMNKW; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 36 "lexer.l"
{ return TK_COMMIT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 37 "lexer.l"
{ return TK_CONFLICT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 38 "lexer.l"
{ return TK_CONSTRAINT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 39 "lexer.l"
{ return TK_CREATE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 40 "lexer.l"
{ return TK_JOIN_KW; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 41 "lexer.l"
{ return TK_CURRENT; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 42 "lexer.l"
{ return TK_CTIME_KW; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 43 "lexer.l"
{ return TK_CTIME_KW; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 44 "lexer.l"
{ return TK_CTIME_KW; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 45 "lexer.l"
{ return TK_DATABASE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 46 "lexer.l"
{ return TK_DEFAULT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 47 "lexer.l"
{ return TK_DEFERRABLE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 48 "lexer.l"
{ return TK_DEFERRED; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 49 "lexer.l"
{ return TK_DELETE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 50 "lexer.l"
{ return TK_DESC; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 51 "lexer.l"
{ return TK_DETACH; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 52 "lexer.l"
{ return TK_DISTINCT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 53 "lexer.l"
{ return TK_DO; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 54 "lexer.l"
{ return TK_DROP; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 55 "lexer.l"
{ return TK_EACH; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 56 "lexer.l"
{ return TK_ELSE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 57 "lexer.l"
{ return TK_END; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 58 "lexer.l"
{ return TK_EQ; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 59 "lexer.l"
{ return TK_ESCAPE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 60 "lexer.l"
{ return TK_EXCEPT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 61 "lexer.l"
{ return TK_EXCLUSIVE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 62 "lexer.l"
{ return TK_EXISTS; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 63 "lexer.l"
{ return TK_EXPLAIN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 64 "lexer.l"
{ return TK_FAIL; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 65 "lexer.l"
{ return TK_FILTER; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 66 "lexer.l"
{ return TK_FOLLOWING; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 67 "lexer.l"
{ return TK_FOR; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 68 "lexer.l"
{ return TK_FOREIGN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 69 "lexer.l"
{ return TK_FROM; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 70 "lexer.l"
{ return TK_LIKE_KW; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 71 "lexer.l"
{ return TK_GROUP; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 72 "lexer.l"
{ return TK_HAVING; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 73 "lexer.l"
{ return TK_IF; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 74 "lexer.l"
{ return TK_IGNORE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 75 "lexer.l"
{ return TK_IMMEDIATE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 76 "lexer.l"
{ return TK_IN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 77 "lexer.l"
{ return TK_INDEX; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 78 "lexer.l"
{ return TK_INDEXED; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 79 "lexer.l"
{ return TK_INITIALLY; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 80 "lexer.l"
{ return TK_JOIN_KW; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 81 "lexer.l"
{ return TK_INSERT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 82 "lexer.l"
{ return TK_INSTEAD; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 83 "lexer.l"
{ return TK_INTERSECT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 84 "lexer.l"
{ return TK_INTO; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 85 "lexer.l"
{ return TK_IS; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 86 "lexer.l"
{ return TK_ISNULL; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 87 "lexer.l"
{ return TK_JOIN; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 88 "lexer.l"
{ return TK_KEY; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 89 "lexer.l"
{ return TK_JOIN_KW; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 90 "lexer.l"
{ return TK_LIKE_KW; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 91 "lexer.l"
{ return TK_LIMIT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 92 "lexer.l"
{ return TK_MATCH; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 93 "lexer.l"
{ return TK_NO; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 94 "lexer.l"
{ return TK_NOT; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 95 "lexer.l"
{ return TK_NOTHING; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 96 "lexer.l"
{ return TK_NOTNULL; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 97 "lexer.l"
{ return TK_NULL; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 98 "lexer.l"
{ return TK_OF; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 99 "lexer.l"
{ return TK_OFFSET; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 100 "lexer.l"
{ return TK_ON; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 101 "lexer.l"
{ return TK_OR; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 102 "lexer.l"
{ return TK_ORDER; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 103 "lexer.l"
{ return TK_JOIN_KW; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 104 "lexer.l"
{ return TK_OVER; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 105 "lexer.l"
{ return TK_PARTITION; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 106 "lexer.l"
{ return TK_PLAN; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 107 "lexer.l"
{ return TK_PRAGMA; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 108 "lexer.l"
{ return TK_PRECEDING; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 109 "lexer.l"
{ return TK_PRIMARY; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 110 "lexer.l"
{ return TK_QUERY; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 111 "lexer.l"
{ return TK_RAISE; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 112 "lexer.l"
{ return TK_RANGE; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 113 "lexer.l"
{ return TK_RECURSIVE; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 114 "lexer.l"
{ return TK_REFERENCES; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 115 "lexer.l"
{ return TK_LIKE_KW; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 116 "lexer.l"
{ return TK_REINDEX; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 117 "lexer.l"
{ return TK_RELEASE; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 118 "lexer.l"
{ return TK_RENAME; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 119 "lexer.l"
{ return TK_REPLACE; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 120 "lexer.l"
{ return TK_RESTRICT; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 121 "lexer.l"
{ return TK_JOIN_KW; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 122 "lexer.l"
{ return TK_ROLLBACK; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 123 "lexer.l"
{ return TK_ROW; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 124 "lexer.l"
{ return TK_ROWS; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 125 "lexer.l"
{ return TK_SAVEPOINT; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 126 "lexer.l"
{ return TK_SELECT; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 127 "lexer.l"
{ return TK_SET; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 128 "lexer.l"
{ return TK_TABLE; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 129 "lexer.l"
{ return TK_TEMP; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 130 "lexer.l"
{ return TK_TEMP; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 131 "lexer.l"
{ return TK_THEN; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 132 "lexer.l"
{ return TK_TO; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 133 "lexer.l"
{ return TK_TRANSACTION; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 134 "lexer.l"
{ return TK_TRIGGER; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 135 "lexer.l"
{ return TK_UNBOUNDED; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 136 "lexer.l"
{ return TK_UNION; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 137 "lexer.l"
{ return TK_UNIQUE; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 138 "lexer.l"
{ return TK_UPDATE; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 139 "lexer.l"
{ return TK_USING; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 140 "lexer.l"
{ return TK_VACUUM; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 141 "lexer.l"
{ return TK_VALUES; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 142 "lexer.l"
{ return TK_VIEW; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 143 "lexer.l"
{ return TK_VIRTUAL; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 144 "lexer.l"
{ return TK_WHEN; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 145 "lexer.l"
{ return TK_WHERE; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 146 "lexer.l"
{ return TK_WINDOW; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 147 "lexer.l"
{ return TK_WITH; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 148 "lexer.l"
{ return TK_WITHOUT; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 150 "lexer.l"
{ return TK_BITAND; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 151 "lexer.l"
{ return TK_BITOR; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 152 "lexer.l"
{ return TK_BITNOT; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 153 "lexer.l"
{ return TK_BLOB; }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 154 "lexer.l"
{ return TK_COMMA; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 155 "lexer.l"
{ return TK_CONCAT; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 156 "lexer.l"
{ return TK_DOT; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 157 "lexer.l"
{ return TK_FLOAT; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 158 "lexer.l"
{ return TK_GE; }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 159 "lexer.l"
{ return TK_GT; }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 160 "lexer.l"
{ return TK_INTEGER; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 161 "lexer.l"
{ return TK_LE; }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 162 "lexer.l"
{ return TK_LP; }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 163 "lexer.l"
{ return TK_LT; }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 164 "lexer.l"
{ return TK_MINUS; }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 165 "lexer.l"
{ return TK_NE; }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 166 "lexer.l"
{ return TK_PLUS; }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 167 "lexer.l"
{ return TK_REM; }
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 168 "lexer.l"
{ return TK_RP; }
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 169 "lexer.l"
{ return TK_RSHIFT; }
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 170 "lexer.l"
{ return TK_SLASH; }
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 171 "lexer.l"
{ return TK_STAR; }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 172 "lexer.l"
{ return TK_STRING; }
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 173 "lexer.l"
{ return TK_SEMI; }
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 174 "lexer.l"
{ yylval->strval = strdup(yytext); return TK_ID; }
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 175 "lexer.l"

	YY_BREAK
case 163:
YY_RULE_SETUP
#line 176 "lexer.l"
ECHO;
	YY_BREAK
#line 1917 "lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 599 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 599 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 598);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp , yyscan_t yyscanner)
{
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = yyg->yy_n_chars + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	yy_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf ,yyscanner );

	yyfree((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "yyset_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "yyset_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void yyset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int yylex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */

int yylex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    yyset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 176 "lexer.l"



void yyerror(parse_node **s, yyscan_t scanner, char const *msg) {
  fprintf(stderr, "Error: %s\n", msg);
}

