# CMake generated Testfile for 
# Source directory: /Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator
# Build directory: /Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(quickstep_queryoptimizer_tests_physicalgenerator_commonsubexpression "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/CommonSubexpression.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/CommonSubexpression.test")
add_test(quickstep_queryoptimizer_tests_physicalgenerator_copy "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/Copy.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/Copy.test")
add_test(quickstep_queryoptimizer_tests_physicalgenerator_create "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/Create.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/Create.test")
add_test(quickstep_queryoptimizer_tests_physicalgenerator_delete "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/Delete.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/Delete.test")
add_test(quickstep_queryoptimizer_tests_physicalgenerator_drop "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/Drop.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/Drop.test")
add_test(quickstep_queryoptimizer_tests_physicalgenerator_index "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/Index.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/Index.test")
add_test(quickstep_queryoptimizer_tests_physicalgenerator_insert "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/Insert.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/Insert.test")
add_test(quickstep_queryoptimizer_tests_physicalgenerator_join "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/Join.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/Join.test")
add_test(quickstep_queryoptimizer_tests_physicalgenerator_select "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/Select.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/Select.test")
add_test(quickstep_queryoptimizer_tests_physicalgenerator_update "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/Update.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/Update.test")
add_test(quickstep_queryoptimizer_tests_physicalgenerator_hustlefirstquery "../quickstep_queryoptimizer_tests_OptimizerTextTest" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/hustlefirstquery.test" "/Users/kevingaffney/Dev/hustle/optimizer/lib/quickstep/query_optimizer/tests/physical_generator/hustlefirstquery.test")
